// BlueprintGeneratedClass AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UAthenaQuestFunctionLibrary_C : UBlueprintFunctionLibrary {

	void Athena_CheckActorHasTags(struct AActor* TargetActor, struct FGameplayTagContainer TagsToCheck, bool OnlyExactMatch, struct UObject* __WorldContext, bool& bDidActorHaveTags); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_CheckActorHasTags // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_PartyAssistCheck(struct AFortPlayerController* PlayerController, struct FName ObjectiveBackendName, struct UObject* __WorldContext, bool& bIsAssistingObjective, bool& bIsValidPlayerController); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_PartyAssistCheck // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_PlayQuestRewardFeedback(bool PlayFX_onPlayer?, struct USoundBase* Success_Sound, struct UParticleSystem* Success_Particles, struct UNiagaraSystem* Success_Niagara, struct UForceFeedbackEffect* Success_Shake, struct AActor* QuestActor, struct AFortPlayerPawn* PlayerPawn, struct FTransform Effect_Transform, struct UObject* __WorldContext); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_PlayQuestRewardFeedback // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	bool Athena_IsCreativeOrPlaygroundPlaylist(struct FGameplayTagContainer& TagContainer, struct UObject* __WorldContext); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_IsCreativeOrPlaygroundPlaylist // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_CheckCreativeMode(struct AGameStateBase* InGameState, struct UObject* __WorldContext, bool& CanCompleteQuest); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_CheckCreativeMode // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_QuestObjectiveCounter(struct AFortPlayerController* FortPlayerControllerAthena, struct UFortQuestItemDefinition* ObjectiveItem, struct FDataTableRowHandle ObjectiveStat, struct UObject* __WorldContext, int32_t& QuestCountAchieved, int32_t& QuestCountRequired, bool& CountSuccessfullyReturned); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_QuestObjectiveCounter // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_GiveQuestUpdateToPlayers(struct UFortQuestItemDefinition* InQuestItemRef, struct FName ObjectiveBackendName, struct FDataTableRowHandle ObjectiveStatEvent, struct TArray<struct AFortPlayerController*>& PlayerControllersForUpdate, struct UObject* __WorldContext); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_GiveQuestUpdateToPlayers // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_CheckQuestAndObjectiveCompletionMP(struct TArray<struct AFortPlayerController*>& InPlayerControlle, struct UFortQuestItemDefinition* InQuestItemRef, struct FName ObjectiveBackendName, struct UObject* __WorldContext, bool& QuestIsValid, bool& QuestCompleted, bool& ObjectiveCompleted); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_CheckQuestAndObjectiveCompletionMP // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_CheckQuestAndObjectiveCompletion(struct AFortPlayerController* InPlayerControlle, struct UFortQuestItemDefinition* InQuestItemRef, struct FName ObjectiveBackendName, struct UObject* __WorldContext, bool& QuestIsValid, bool& QuestCompleted, bool& ObjectiveCompleted); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_CheckQuestAndObjectiveCompletion // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_HasPlayerCompletedQuest(struct AFortPlayerController* InPlayerControlle, struct UFortQuestItemDefinition* InQuestItemRef, struct UObject* __WorldContext, bool& HasQuest, bool& QuestCompleted); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_HasPlayerCompletedQuest // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Athena_HasQuest(struct AFortPlayerController* InPlayerControlle, struct UFortQuestItemDefinition* InQuestItemRef, struct UObject* __WorldContext, bool& PlayerHasQuest); // Function AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_HasQuest // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
};

