// BlueprintGeneratedClass SocialTagsFunctionLibrary.SocialTagsFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct USocialTagsFunctionLibrary_C : UBlueprintFunctionLibrary {

	void InterpolateTagContentColors(struct UTextBlock* TagName, struct UImage* CheckMark, struct FLinearColor CurrentTagContentColor, struct FLinearColor TargetTagContentColor, double HoveredTagContentLerpAlpha, struct UObject* __WorldContext); // Function SocialTagsFunctionLibrary.SocialTagsFunctionLibrary_C.InterpolateTagContentColors // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void InterpolateTagBorderColors(struct UMaterialInstanceDynamic* TagBorderMaterial, struct FName NameInnerColor, struct FLinearColor CurrentInnerColor, struct FLinearColor TargetInnerColor, struct FName NameOuterColor, struct FLinearColor CurrentOuterColor, struct FLinearColor TargetOuterColor, double HoveredBorderColorLerpAlpha, struct FTimerHandle& ColorLerpTimeHandle, struct UObject* WorldContext, struct UObject* __WorldContext); // Function SocialTagsFunctionLibrary.SocialTagsFunctionLibrary_C.InterpolateTagBorderColors // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void ClearLerpColorTimer(double ColorLerpAlpha, struct FTimerHandle& ColorLerpTimeHandle, struct UObject* __WorldContext); // Function SocialTagsFunctionLibrary.SocialTagsFunctionLibrary_C.ClearLerpColorTimer // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void InterpolateMaterialColor(struct UMaterialInstanceDynamic* Material, struct FName ColorParameterName, struct FLinearColor CurrentColor, struct FLinearColor TargetColor, double ColorLerpAlpha, struct UObject* __WorldContext); // Function SocialTagsFunctionLibrary.SocialTagsFunctionLibrary_C.InterpolateMaterialColor // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void InterpolateTagBorderOuterStrokeColor(struct UBorder* TagBorder, struct FName TagOuterStrokeColor, struct FSidebarSocialTagCategoryStructure& SidebarSocialTagCategoryStructure, double TagBorderInnerColorHoveredLerpValue, struct FTimerHandle& TagBorderInnerColorHoveredLerpTimeHandle, struct UWidget* TagWidgetReference, struct FLinearColor TagOuterStrokeColorUnhovered, struct UObject* __WorldContext); // Function SocialTagsFunctionLibrary.SocialTagsFunctionLibrary_C.InterpolateTagBorderOuterStrokeColor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void InterpolateTagBorderGradientColor(struct UBorder* TagBorder, struct FName , struct FName , struct FSidebarSocialTagCategoryStructure& SidebarSocialTagCategoryStructure, double TagBorderInnerColorHoveredLerpValue, struct FTimerHandle& TagBorderInnerColorHoveredLerpTimeHandle, struct UWidget* TagWidgetReference, struct UObject* __WorldContext); // Function SocialTagsFunctionLibrary.SocialTagsFunctionLibrary_C.InterpolateTagBorderGradientColor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
	void Get Sidebar Social Tag Category Structure(struct FString TagCategory, struct UObject* __WorldContext, struct FSidebarSocialTagCategoryStructure& SidebarSocialTagCategoryStructure); // Function SocialTagsFunctionLibrary.SocialTagsFunctionLibrary_C.Get Sidebar Social Tag Category Structure // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xd67374
};

