// VerseClass VerseExperimental.$SolarisSignatureFunctionOuter
// Size: 0x28 (Inherited: 0x28)
struct U$SolarisSignatureFunctionOuter : UObject {
};

// VerseClass VerseExperimental.date_time_ticks
// Size: 0x70 (Inherited: 0x28)
struct Udate_time_ticks : UObject {
	int64_t __verse_0x8DE5F121_NanosecondsPerTick; // 0x28(0x08)
	int64_t __verse_0x358147B9_TicksPerDay; // 0x30(0x08)
	int64_t __verse_0x5C0949D3_TicksPerHour; // 0x38(0x08)
	int64_t __verse_0x59DFB831_TicksPerMicrosecond; // 0x40(0x08)
	int64_t __verse_0xD20E16AF_TicksPerMillisecond; // 0x48(0x08)
	int64_t __verse_0x4420B794_TicksPerMinute; // 0x50(0x08)
	int64_t __verse_0x3E0178E0_TicksPerSecond; // 0x58(0x08)
	int64_t __verse_0xA7911900_TicksPerWeek; // 0x60(0x08)
	int64_t __verse_0xE371C089_TicksPerYear; // 0x68(0x08)

	void $InitCDO(); // Function VerseExperimental.date_time_ticks.$InitCDO // (None) // @ game+0xd67374
};

// VerseClass VerseExperimental.VerseExperimental
// Size: 0x28 (Inherited: 0x28)
struct UVerseExperimental : UObject {

	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2f_27_L_Ntime__span_M_Nfloat_R(struct Ftuple_Ltime__span_Mfloat_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2f_27_L_Ntime__span_M_Nfloat_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ndate__time_M_Ntime__span_R(struct Ftuple_Ldate__time_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ndate__time_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ntime__span_R // (Final|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xd67374
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2b_27_L_Ndate__time_M_Ntime__span_R(struct Ftuple_Ldate__time_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2b_27_L_Ndate__time_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2b_27_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2b_27_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2a_27_L_Ntime__span_M_Nfloat_R(struct Ftuple_Ltime__span_Mfloat_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2a_27_L_Ntime__span_M_Nfloat_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2a_27_L_Nfloat_M_Ntime__span_R(struct Ftuple_Lfloat_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2a_27_L_Nfloat_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	char _L_2fVerse_2eorg_2fVerseExperimental_N_RValidateDateTime_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R(struct Ftuple_Lint_Mint_Mint_Mint_Mint_Mint_Mint_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RValidateDateTime_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637042c
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RValidate_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RValidate_L_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RUtcNow(struct Ftuple_L_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RUtcNow // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370424
	VerseStringProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RToString_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RToString_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637041c
	VerseStringProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RToString_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RToString_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370414
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ntime__span_M_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637040c
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ndate__time_M_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703fc
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ndate__time_M_Ntime__span_R(struct Ftuple_Ldate__time_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ndate__time_M_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370404
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeNegate_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeNegate_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703f4
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeMultiply_L_Ntime__span_M_Nfloat_R(struct Ftuple_Ltime__span_Mfloat_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeMultiply_L_Ntime__span_M_Nfloat_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703ec
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeDivide_L_Ntime__span_M_Nfloat_R(struct Ftuple_Ltime__span_Mfloat_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeDivide_L_Ntime__span_M_Nfloat_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703e4
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeAdd_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeAdd_L_Ntime__span_M_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703dc
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeAdd_L_Ndate__time_M_Ntime__span_R(struct Ftuple_Ldate__time_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeAdd_L_Ndate__time_M_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703d4
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RLessEqual_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RLessEqual_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RLessEqual_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RLessEqual_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RLess_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RLess_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RLess_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RLess_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RGreaterEqual_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGreaterEqual_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RGreaterEqual_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGreaterEqual_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RGreater_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGreater_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RGreater_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGreater_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xd67374
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetYear_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetYear_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703cc
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalSeconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalSeconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703c4
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMinutes_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMinutes_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703bc
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMilliseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMilliseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703b4
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMicroseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMicroseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703ac
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalHours_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalHours_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63703a4
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalDays_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalDays_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637039c
	struct Ftime_of_day_parts _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTimeOfDay_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTimeOfDay_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370394
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetSeconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetSeconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637038c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetSeconds_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetSeconds_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370384
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetNanoseconds_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetNanoseconds_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370374
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetNanoseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetNanoseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637037c
	enum class month_of_year _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMonthOfYear_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMonthOfYear_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370364
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMonth_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMonth_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637036c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMinutes_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMinutes_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637035c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMinutes_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMinutes_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370354
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMilliseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMilliseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637034c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMilliseconds_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMilliseconds_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370344
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMicroseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMicroseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637033c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMicroseconds_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMicroseconds_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370334
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetHours_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetHours_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637032c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetHours_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetHours_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370324
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetDays_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetDays_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637031c
	enum class day_of_week _L_2fVerse_2eorg_2fVerseExperimental_N_RGetDayOfWeek_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetDayOfWeek_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x637030c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetDay_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetDay_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370314
	struct Fdate_parts _L_2fVerse_2eorg_2fVerseExperimental_N_RGetDate_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetDate_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x6370304
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RDaysInYear_L_Nint_R(int64_t __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RDaysInYear_L_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63702fc
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RDaysInMonth_L_Nint_M_Nint_R(struct Ftuple_Lint_Mint_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RDaysInMonth_L_Nint_M_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63702f4
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RDateTimeMin(struct Ftuple_L_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RDateTimeMin // (Final|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xd67374
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RDateTimeMax(struct Ftuple_L_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RDateTimeMax // (Final|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xd67374
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RCreateTimeSpan_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R(struct Ftuple_Lint_Mint_Mint_Mint_Mint_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RCreateTimeSpan_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63702ec
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RCreateDateTime_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R(struct Ftuple_Lint_Mint_Mint_Mint_Mint_Mint_Mint_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RCreateDateTime_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63702e4
	struct Ftime_span time_span$Factory(); // Function VerseExperimental.VerseExperimental.time_span$Factory // (Static|HasOutParms) // @ game+0xd67374
	struct Ftime_of_day_parts time_of_day_parts$Factory(); // Function VerseExperimental.VerseExperimental.time_of_day_parts$Factory // (Static|HasOutParms) // @ game+0xd67374
	struct Fdate_parts date_parts$Factory(); // Function VerseExperimental.VerseExperimental.date_parts$Factory // (Static|HasOutParms) // @ game+0xd67374
	struct Fdate_time date_time$Factory(); // Function VerseExperimental.VerseExperimental.date_time$Factory // (Static|HasOutParms) // @ game+0xd67374
	void $InitCDO(); // Function VerseExperimental.VerseExperimental.$InitCDO // (None) // @ game+0xd67374
};

